"""The personal layer against a real Postgres (issue #16).

Slice 11 records the owner-specific layer — Goals, Markers, Decisions — through the
`personal` service and links it to the impersonal evidence layer by Concept
overlap. This drives those repository reads and `personal` writes — the same code
the HTTP API wraps — over a real Postgres + pgvector, starting from a genuinely
admitted Candidate (the Slice-8 path) so the Concepts a Decision overlaps with are
the ones extraction actually built. Concept mentions are resolved through the same
`FakeEmbedder`/`ConceptNormalizer` the admit pipeline uses, so a personal-layer
mention merges onto the canonical Concept the Body of Knowledge already minted.

Covers, per the acceptance criteria: Goal/Marker/Decision CRUD; a Marker being
append-only with derived out-of-range and a viewable series; a Decision carrying
its own actual parameters distinct from the Protocol it implements; "adopt a
Protocol"; and suggest-then-confirm links generated by Concept overlap and
individually confirmable.
"""

from __future__ import annotations

from datetime import datetime, timezone

import psycopg
import pytest

from health_bok import personal, review
from health_bok.repository import Repository
from tests.fakes import FakeExtractor
from tests.seed import seed_processed_video
from tests.test_admission import (
    RAPAMYCIN_CLAIM,
    drain_daily,
    make_extraction,
    normalizer,
)

VIDEO_ID = "vid_personal"
AT = datetime(2026, 3, 1, 8, 0, tzinfo=timezone.utc)


def _admit_bok(repo: Repository) -> None:
    """Admit a video so the BoK has Concepts/Claims/Protocols to overlap against."""
    seed_processed_video(repo, video_id=VIDEO_ID)
    review.approve_candidate(VIDEO_ID, repo=repo)
    drain_daily(FakeExtractor(make_extraction()), repo)


def _concepts_by_name(repo: Repository) -> dict:
    return {c.name: c for c in repo.list_concepts()}


# -- Goals ------------------------------------------------------------------


def test_goal_records_with_concepts_and_shows_serving_decisions(conn):
    repo = Repository(conn)
    _admit_bok(repo)

    # Record a Goal concerning a Concept the BoK already knows ("rapamycin"); the
    # mention normalizes onto that same canonical Concept, not a duplicate.
    goal_id = personal.record_goal(
        title="Lower cardiovascular risk",
        detail="Keep apoB and inflammation low.",
        concepts=["rapamycin"],
        normalizer=normalizer(repo),
        repo=repo,
    )

    goals = repo.list_goals()
    assert [g.title for g in goals] == ["Lower cardiovascular risk"]
    goal = goals[0]
    assert [c.name for c in goal.concepts] == ["rapamycin"]
    assert goal.concepts[0].id == _concepts_by_name(repo)["rapamycin"].id  # merged
    assert goal.served_by == []  # an unmet Goal — nothing serves it yet

    # A Decision that serves the Goal makes it visible on the Goal (AC: "see which
    # Decisions serve a Goal").
    decision_id = personal.record_decision(
        action="Take rapamycin", dose="6mg", timing=None, frequency="weekly",
        duration=None, started_at=AT, ended_at=None, note=None,
        concepts=["rapamycin"], implements_protocol_id=None,
        normalizer=normalizer(repo), repo=repo,
    )
    assert personal.link_decision(
        decision_id, target_type="goal", target_id=goal_id, repo=repo
    ) is True

    reread = repo.get_goal(goal_id)
    assert [d.action for d in reread.served_by] == ["Take rapamycin"]

    # Deleting the serving Decision returns the Goal to unmet, no edge left dangling.
    assert personal.delete_decision(decision_id, repo=repo) is True
    assert repo.get_goal(goal_id).served_by == []


def test_delete_goal_removes_it_and_its_edges(conn):
    repo = Repository(conn)
    _admit_bok(repo)
    goal_id = personal.record_goal(
        title="Improve sleep", detail=None, concepts=["sleep"],
        normalizer=normalizer(repo), repo=repo,
    )
    assert _edges_touching(conn, "goal", goal_id) == 1  # its one `references` edge
    assert personal.delete_goal(goal_id, repo=repo) is True
    assert repo.get_goal(goal_id) is None
    assert _edges_touching(conn, "goal", goal_id) == 0
    assert "sleep" in _concepts_by_name(repo)  # the Concept hub is untouched
    assert personal.delete_goal(goal_id, repo=repo) is False  # clean no-op


# -- Markers ----------------------------------------------------------------


def test_marker_is_append_only_time_series_with_derived_out_of_range(conn):
    repo = Repository(conn)
    norm = normalizer(repo)

    # Three apoB readings over time: high → still high → in range. apoB has a
    # one-sided reference range (only an upper bound).
    r1 = personal.record_marker(
        concept="apoB", value=130, unit="mg/dL", reference_low=None,
        reference_high=90, measured_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
        normalizer=norm, repo=repo,
    )
    personal.record_marker(
        concept="apoB", value=110, unit="mg/dL", reference_low=None,
        reference_high=90, measured_at=datetime(2026, 3, 1, tzinfo=timezone.utc),
        normalizer=norm, repo=repo,
    )
    personal.record_marker(
        concept="apoB", value=85, unit="mg/dL", reference_low=None,
        reference_high=90, measured_at=datetime(2026, 6, 1, tzinfo=timezone.utc),
        normalizer=norm, repo=repo,
    )

    # The series view: one entry per Concept, latest reading + full count.
    series = repo.list_marker_series()
    assert len(series) == 1
    apob = series[0]
    assert apob.concept.name == "apoB"
    assert apob.reading_count == 3
    assert apob.latest.value == 85.0  # newest by measured_at
    assert apob.latest.out_of_range is False  # 85 <= 90 → derived in range

    # The history renders as a series, newest first, out-of-range derived per row.
    history = repo.marker_history(apob.concept.id)
    assert [h.value for h in history] == [85.0, 110.0, 130.0]
    assert [h.out_of_range for h in history] == [False, True, True]

    # A two-sided range derives both directions; a value inside is in range.
    personal.record_marker(
        concept="fasting glucose", value=60, unit="mg/dL", reference_low=70,
        reference_high=99, measured_at=AT, normalizer=norm, repo=repo,
    )
    glucose = {s.concept.name: s for s in repo.list_marker_series()}["fasting glucose"]
    assert glucose.latest.out_of_range is True  # 60 < 70 → below the low bound

    # Append-only: a reading is an immutable dated snapshot, never overwritten.
    with pytest.raises(psycopg.errors.RaiseException):
        with conn.cursor() as cur:
            cur.execute("UPDATE markers SET value = 1 WHERE id = %s", (r1,))
    conn.rollback()
    with pytest.raises(psycopg.errors.RaiseException):
        with conn.cursor() as cur:
            cur.execute("DELETE FROM markers WHERE id = %s", (r1,))
    conn.rollback()
    assert {h.value for h in repo.marker_history(apob.concept.id)} == {85.0, 110.0, 130.0}


# -- Decisions, adopt & suggest-then-confirm --------------------------------


def test_decision_carries_own_parameters_and_adopts_a_protocol(conn):
    repo = Repository(conn)
    _admit_bok(repo)
    protocol = repo.list_protocols()[0]  # "Take creatine monohydrate", dose 5g
    assert protocol.dose == "5g"

    # Adopt the Protocol: the Decision pre-fills from it but records the owner's
    # *own* actual dose (3g, a deliberate deviation) — distinct from the Protocol's.
    decision_id = personal.record_decision(
        action="Take creatine monohydrate", dose="3g", timing="morning",
        frequency="daily", duration=None, started_at=AT, ended_at=None,
        note="Half the recommended dose to start.", concepts=[],
        implements_protocol_id=protocol.id,
        normalizer=normalizer(repo), repo=repo,
    )

    decision = repo.get_decision(decision_id)
    assert decision.dose == "3g"  # the owner's actual parameter, not the Protocol's 5g
    assert [p.action for p in decision.implements] == ["Take creatine monohydrate"]
    # Adopting inherits the Protocol's Concepts, so overlap works immediately.
    assert [c.name for c in decision.concepts] == ["creatine monohydrate"]


def test_suggested_links_are_generated_by_overlap_and_individually_confirmable(conn):
    repo = Repository(conn)
    _admit_bok(repo)
    norm = normalizer(repo)

    # A Goal concerning rapamycin (overlaps the rapamycin Claim and any rapamycin
    # Decision); recorded before the Decision so it can be suggested.
    goal_id = personal.record_goal(
        title="Extend healthspan", detail=None, concepts=["rapamycin"],
        normalizer=norm, repo=repo,
    )

    # A Decision concerning both rapamycin and creatine — so the suggester finds a
    # Protocol (creatine), a Claim (rapamycin), and a Goal (rapamycin) by overlap.
    decision_id = personal.record_decision(
        action="Adopt a longevity stack", dose=None, timing=None, frequency=None,
        duration=None, started_at=AT, ended_at=None, note=None,
        concepts=["rapamycin", "creatine monohydrate"], implements_protocol_id=None,
        normalizer=norm, repo=repo,
    )

    suggestions = personal.suggest_decision_links(decision_id, repo=repo)
    by_type = {s.target_type: s for s in suggestions}
    assert set(by_type) == {"protocol", "claim", "goal"}  # one relevant of each kind
    assert by_type["protocol"].label == "Take creatine monohydrate"
    assert by_type["protocol"].shared_concepts == ["creatine monohydrate"]
    assert by_type["claim"].label == RAPAMYCIN_CLAIM
    assert by_type["claim"].shared_concepts == ["rapamycin"]
    assert by_type["goal"].target_id == goal_id
    assert by_type["goal"].shared_concepts == ["rapamycin"]

    # Confirm just the Protocol — links are individually confirmable, not all-or-nothing.
    assert personal.link_decision(
        decision_id, target_type="protocol",
        target_id=by_type["protocol"].target_id, repo=repo,
    ) is True

    # The confirmed Protocol drops out of the next round; the other two remain.
    remaining = {s.target_type for s in personal.suggest_decision_links(decision_id, repo=repo)}
    assert remaining == {"claim", "goal"}

    # Confirm the Claim (supporting evidence) and the Goal (served).
    assert personal.link_decision(
        decision_id, target_type="claim", target_id=by_type["claim"].target_id, repo=repo
    ) is True
    assert personal.link_decision(
        decision_id, target_type="goal", target_id=goal_id, repo=repo
    ) is True
    assert personal.suggest_decision_links(decision_id, repo=repo) == []  # all linked

    # A Marker reading motivates the Decision (owner-chosen, not suggested).
    reading_id = personal.record_marker(
        concept="rapamycin", value=1, unit="x", reference_low=None,
        reference_high=None, measured_at=AT, normalizer=norm, repo=repo,
    )
    assert personal.link_decision(
        decision_id, target_type="marker", target_id=reading_id, repo=repo
    ) is True

    # The Decision's rationale is reviewable from one place: supporting evidence
    # (Claims), the Goals it serves, the Protocol it implements, the Marker behind it.
    decision = repo.get_decision(decision_id)
    assert [p.action for p in decision.implements] == ["Take creatine monohydrate"]
    assert [c.text for c in decision.supported_by] == [RAPAMYCIN_CLAIM]
    assert [g.title for g in decision.serves] == ["Extend healthspan"]
    assert [m.id for m in decision.motivated_by] == [reading_id]

    # And the Goal now shows the Decision serving it (no longer unmet).
    assert [d.action for d in repo.get_goal(goal_id).served_by] == ["Adopt a longevity stack"]

    # A confirmed link is detachable; re-confirming is idempotent (no duplicate edge).
    assert personal.unlink_decision(
        decision_id, target_type="goal", target_id=goal_id, repo=repo
    ) is True
    assert repo.get_decision(decision_id).serves == []
    assert personal.link_decision(decision_id, target_type="goal", target_id=goal_id, repo=repo)
    assert personal.link_decision(decision_id, target_type="goal", target_id=goal_id, repo=repo)
    assert len(repo.get_decision(decision_id).serves) == 1  # unique constraint deduped


def test_unknown_link_target_is_rejected(conn):
    repo = Repository(conn)
    _admit_bok(repo)
    decision_id = personal.record_decision(
        action="x", dose=None, timing=None, frequency=None, duration=None,
        started_at=AT, ended_at=None, note=None, concepts=[],
        implements_protocol_id=None, normalizer=normalizer(repo), repo=repo,
    )
    with pytest.raises(personal.UnknownLinkTarget):
        personal.link_decision(decision_id, target_type="concept", target_id=1, repo=repo)
    conn.rollback()


def _edges_touching(conn, node_type: str, node_id: int) -> int:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT count(*) FROM edges WHERE (src_type = %s AND src_id = %s) "
            "OR (dst_type = %s AND dst_id = %s)",
            (node_type, node_id, node_type, node_id),
        )
        return cur.fetchone()[0]
