"""The Impact engine: bidirectional change detection & the inbox (issue #18).

When newly-arrived evidence bears on the owner's choices — or a new choice meets
the existing library — the owner is told, with a reviewable inbox and an audit
trail (CONTEXT.md "Impact"). Detection fires in *either direction*:

  * **forward** — a newly-admitted Claim/Protocol is checked against the existing
    anchors (Decisions, Goals, Markers). Run by the worker after admission.
  * **reverse** — a newly-recorded anchor (a Decision or Goal) is scanned against
    the existing Body of Knowledge (Claims, Protocols). Run after the owner records
    it.

Either way the candidates are generated by shared-Concept overlap — the same
Concept-traversal machinery query is built on (ADR-0008, ADR-0011) — and a
`StanceJudge` (an LLM pass) assigns the Stance to each pair. Overlap alone would
flood the inbox with the merely-related, so the stance is *judged*, not inferred;
an `unrelated` judgement raises nothing (CONTEXT.md "Stance"). Each surviving
finding is persisted as a deduped Impact, so re-runs and overlapping evidence never
nag twice.

A re-extraction supersede (ADR-0005) is the third trigger: when the pipeline can no
longer match a superseded Claim, `supersede_impacts` raises an Impact against any
Decision that Claim supported — changed evidence under a Decision is surfaced, not
silently broken — without an LLM pass, since the supersede itself is the finding.

The lifecycle half drives an Impact `new → reviewed → actioned | dismissed` so it
never re-nags once resolved, with bulk-dismiss for bursts. Actioning records the
Decision the owner revised or created in response — change detection driving
auditable change.

Like the rest of the domain it depends only on the repository and the `StanceJudge`
port, so it is driven in tests with a fake judge over *real* Concept-overlap
candidates from a real Postgres (PRD #1 testing decisions).
"""

from __future__ import annotations

import logging

from .ports import StanceJudge
from .repository import Impact, Repository

logger = logging.getLogger("health_bok.impacts")

# The persisted Stances (CONTEXT.md "Stance"). `unrelated` is judged but never
# stored — it is the discard signal — so it is deliberately absent here and from
# the table's CHECK.
STANCES = frozenset({"reinforces", "contradicts", "refines", "opportunity"})
UNRELATED = "unrelated"

# How many candidate anchors/knowledge a single subject is weighed against, per
# category — a ceiling on the LLM judge calls one detection pass makes. Tunable via
# IMPACT_CANDIDATE_LIMIT.
DEFAULT_CANDIDATE_LIMIT = 25

# The stance a supersede raises (ADR-0005): a supporting Claim the re-extraction
# dropped or materially changed undercuts the Decision's basis — the owner must see
# it, so it lands as a contradiction rather than a gentle refinement.
SUPERSEDE_STANCE = "contradicts"

# Relationship-alerting stances, derived *structurally* from the graph diff — no LLM
# (ADR-0013): a brand-new connection reads as `new_link`; a pair that now holds
# contradicting predicates as `contradicts`; a relationship whose last evidence
# vanished as `eroded`.
NEW_LINK = "new_link"
CONTRADICTS = "contradicts"
ERODED = "eroded"

# Tier-2 notability gate: a structural change that touches no tracked anchor only
# reaches the browsable feed when its Strength clears this threshold, so the feed
# surfaces the well-supported, not every stray edge. A tuning knob (ADR-0013).
DEFAULT_TIER2_STRENGTH_THRESHOLD = 2.0


# -- detection (forward, reverse, supersede) --------------------------------


def detect_for_admitted_video(
    video_id: str,
    *,
    judge: StanceJudge,
    repo: Repository,
    candidate_limit: int = DEFAULT_CANDIDATE_LIMIT,
) -> list[int]:
    """Forward pass over a freshly-admitted video's Claims & Protocols (issue #18).

    Each admitted Claim/Protocol is weighed against the anchors it overlaps by
    Concept. Returns the ids of the Impacts raised. Commits — it runs *after* the
    admission has committed, failure-isolated by the worker, so a judge hiccup never
    undoes a valid admission (ADR-0005).
    """
    raised: list[int] = []
    for claim in repo.admitted_claims(video_id):
        raised += _detect_forward("claim", claim.id, judge, repo, candidate_limit)
    for protocol in repo.admitted_protocols(video_id):
        raised += _detect_forward("protocol", protocol.id, judge, repo, candidate_limit)
    repo.commit()
    logger.info("impact detection for %s raised %d impact(s)", video_id, len(raised))
    return raised


def detect_for_new_anchor(
    anchor_type: str,
    anchor_id: int,
    *,
    judge: StanceJudge,
    repo: Repository,
    candidate_limit: int = DEFAULT_CANDIDATE_LIMIT,
) -> list[int]:
    """Reverse pass: scan the Body of Knowledge for a new Decision/Goal (issue #18).

    The newly-recorded anchor is weighed against the Claims/Protocols it overlaps by
    Concept; an Impact's `source` is always the Claim/Protocol, its `anchor` this new
    Decision/Goal. Returns the Impact ids raised. Commits — it is invoked standalone
    after the anchor was recorded.
    """
    anchor = repo.load_impact_anchor(anchor_type, anchor_id)
    if anchor is None:
        repo.rollback()
        return []
    raised: list[int] = []
    for knowledge in repo.impact_knowledge_candidates(
        anchor_type, anchor_id, limit=candidate_limit
    ):
        stance = _stance(judge, knowledge, anchor)
        if stance is None:
            continue
        impact_id = repo.add_impact(
            knowledge.type, knowledge.id, anchor_type, anchor_id, stance
        )
        if impact_id is not None:
            raised.append(impact_id)
    repo.commit()
    logger.info(
        "reverse impact detection for %s %s raised %d impact(s)",
        anchor_type, anchor_id, len(raised),
    )
    return raised


def supersede_impacts(superseded_claim_id: int, *, repo: Repository) -> list[int]:
    """Raise an Impact against each Decision a superseded Claim supported (ADR-0005).

    Called by re-extraction when it can no longer confidently match a Claim it
    previously extracted: rather than silently break the `Decision → Claim` link, the
    evidence change is surfaced as a `contradicts` Impact on the affected Decision
    (issue #18). No LLM pass — the supersede *is* the finding. Does not commit: the
    re-extraction caller owns the transaction.
    """
    raised: list[int] = []
    for decision_id in repo.decisions_supported_by_claim(superseded_claim_id):
        impact_id = repo.add_impact(
            "claim",
            superseded_claim_id,
            "decision",
            decision_id,
            SUPERSEDE_STANCE,
            detail="A supporting Claim was superseded by re-extraction (ADR-0005).",
        )
        if impact_id is not None:
            raised.append(impact_id)
    logger.info(
        "supersede of claim %s raised %d impact(s)", superseded_claim_id, len(raised)
    )
    return raised


# -- relationship alerting (ADR-0013) ---------------------------------------


def detect_relationship_impacts_for_video(
    video_id: str,
    *,
    repo: Repository,
    now=None,
    strength_threshold: float = DEFAULT_TIER2_STRENGTH_THRESHOLD,
) -> list[int]:
    """Alert on the lateral relationships a freshly-admitted video derived (ADR-0013).

    The relationship-aware forward pass, run by the worker after admission. Each
    relationship the video evidences raises:

      * **Tier-1** — a push Impact on every Goal/Decision tracking a Concept in the
        relationship's subtree (ancestor-or-self of either endpoint), so a
        development in an area the owner cares about reaches the inbox; or
      * **Tier-2** — when it touches no tracked anchor but its Strength clears the
        threshold, a quieter feed entry anchored on the relationship's subject
        Concept (not the inbox).

    The stance is derived structurally — `contradicts` when the pair is now
    contested, else `new_link` — with no LLM pass. Deduped, so re-admission never
    re-nags. Commits; returns the Impact ids raised.
    """
    raised: list[int] = []
    for rel in repo.relation_alerts_for_video(video_id, now=now):
        stance = CONTRADICTS if rel.contested else NEW_LINK
        anchors = repo.anchors_tracking_relation(rel.src_concept_id, rel.dst_concept_id)
        if anchors:
            detail = _relation_detail(rel)
            for anchor_type, anchor_id in anchors:
                impact_id = repo.add_impact(
                    "relation", rel.relation_id, anchor_type, anchor_id, stance,
                    tier=1, detail=detail,
                )
                if impact_id is not None:
                    raised.append(impact_id)
        elif rel.strength >= strength_threshold:
            impact_id = repo.add_impact(
                "relation", rel.relation_id, "concept", rel.src_concept_id, stance,
                tier=2, detail=_relation_detail(rel),
            )
            if impact_id is not None:
                raised.append(impact_id)
    repo.commit()
    logger.info(
        "relationship alerting for %s raised %d impact(s)", video_id, len(raised)
    )
    return raised


def detect_scope_widening(
    anchor_type: str, anchor_id: int, *, repo: Repository
) -> list[int]:
    """One *summary* Impact for the backlog a newly-tracked anchor pulls in (ADR-0013).

    When the owner records a Goal/Decision (or otherwise widens tracked scope), the
    relationships already sitting under each Concept it tracks must not detonate one
    Impact each. Instead this raises a single Tier-1 *summary* per newly-tracked
    Concept — "12 existing connections now in scope" — and then only relationships
    arriving *afterwards* push (handled by the per-video pass). Deduped on
    (anchor, concept, new_link), so re-running never re-nags. Commits.
    """
    raised: list[int] = []
    for concept_id in repo.concept_ids_for(anchor_type, anchor_id):
        backlog = repo.count_relations_touching_subtree(concept_id)
        if backlog == 0:
            continue
        impact_id = repo.add_impact(
            "concept", concept_id, anchor_type, anchor_id, NEW_LINK, tier=1,
            detail=f"{backlog} existing connection(s) now in scope — review?",
        )
        if impact_id is not None:
            raised.append(impact_id)
    repo.commit()
    logger.info(
        "scope-widening for %s %s raised %d summary impact(s)",
        anchor_type, anchor_id, len(raised),
    )
    return raised


def delete_claim_with_alerts(claim_id: int, *, repo: Repository) -> tuple[bool, list[int]]:
    """Delete a Claim and raise an `eroded` Impact for any Decision-relied-on
    relationship it was the last evidence for (ADR-0013, ADR-0005).

    Self-healing made audible: deleting (or superseding) the last Claim behind a
    relationship removes it — but if a Decision tracked it, the vanishing basis must
    not go unnoticed (user story 34). Captures the relationships the Claim evidences,
    deletes the Claim (which prunes any now-unevidenced relationship), then raises an
    `eroded` Impact on each Decision tracking a relationship that did not survive.
    Returns `(existed, raised_impact_ids)`. Commits.
    """
    before = repo.relations_evidenced_by_claim_detailed(claim_id)
    existed = repo.delete_claim(claim_id)
    surviving = repo.existing_relation_ids([rel.id for rel in before])
    raised: list[int] = []
    for rel in before:
        if rel.id in surviving:
            continue  # still evidenced by another Claim — not eroded
        for anchor_type, anchor_id in repo.anchors_tracking_relation(
            rel.src_concept_id, rel.dst_concept_id
        ):
            if anchor_type != "decision":
                continue  # `eroded` is a Decision-relied-on event (user story 34)
            impact_id = repo.add_impact(
                "relation", rel.id, "decision", anchor_id, ERODED, tier=1,
                detail=(
                    f"The relationship '{rel.src_name} {rel.predicate} {rel.dst_name}' "
                    "a Decision relied on lost its last evidence (ADR-0013)."
                ),
            )
            if impact_id is not None:
                raised.append(impact_id)
    repo.commit()
    logger.info("deletion of claim %s raised %d eroded impact(s)", claim_id, len(raised))
    return existed, raised


def _relation_detail(rel) -> str:
    """The "why" line on a relationship Impact — its rendered link and support."""
    contested = ", contested" if rel.contested else ""
    return (
        f"{rel.src_name} {rel.predicate} {rel.dst_name} "
        f"({rel.creator_count} creator(s){contested})"
    )


# -- inbox & lifecycle ------------------------------------------------------

# The unresolved inbox: an Impact still wanting the owner's attention. A resolved
# (`actioned`/`dismissed`) Impact keeps its row — for the audit trail and for
# dedup — but drops out of the default inbox so it never re-nags.
_UNRESOLVED = ["new", "reviewed"]


def inbox(
    *,
    stance: str | None = None,
    anchor_type: str | None = None,
    anchor_id: int | None = None,
    state: str | None = None,
    repo: Repository,
) -> list[Impact]:
    """The Impact inbox: unresolved *Tier-1* findings, filterable by stance and anchor.

    With no `state` given it shows the unresolved `new`/`reviewed` Impacts (the
    nagging ones); an explicit `state` narrows to exactly that lifecycle position
    (e.g. to review what was `dismissed`). Only the push tier reaches the inbox; the
    quieter Tier-2 structural changes live in `tier2_feed` (ADR-0013). Read-only.
    """
    states = [state] if state is not None else _UNRESOLVED
    return repo.list_impacts(
        stance=stance, anchor_type=anchor_type, anchor_id=anchor_id, states=states,
        tier=1,
    )


def tier2_feed(
    *, stance: str | None = None, repo: Repository
) -> list[Impact]:
    """The quieter Tier-2 browsable feed of notable structural changes (ADR-0013).

    Field-wide relationship developments that touch no tracked anchor but cleared
    the Strength threshold — available on demand, deliberately *not* in the push
    inbox, so a discovery is findable without flooding the owner. Read-only.
    """
    return repo.list_impacts(stance=stance, states=_UNRESOLVED, tier=2)


def review_impact(impact_id: int, *, repo: Repository) -> bool:
    """Mark an Impact `reviewed` — the owner has seen it (issue #18). ``False`` if gone."""
    return _transition(impact_id, "reviewed", repo)


def dismiss_impact(impact_id: int, *, repo: Repository) -> bool:
    """Dismiss an Impact so it never re-nags (issue #18). ``False`` if it's gone."""
    return _transition(impact_id, "dismissed", repo)


def action_impact(impact_id: int, *, decision_id: int, repo: Repository) -> bool:
    """Action an Impact, recording the Decision it produced (issue #18).

    The owner revised or created a Decision in response (e.g. to a `contradicts` or
    `opportunity`); this marks the Impact `actioned` and records the link, leaving an
    audit trail of change detection driving change. ``False`` if the Impact is gone.
    """
    if repo.set_impact_state(impact_id, "actioned", actioned_decision_id=decision_id):
        repo.commit()
        logger.info("actioned impact %s -> decision %s", impact_id, decision_id)
        return True
    repo.rollback()
    return False


def bulk_dismiss(impact_ids: list[int], *, repo: Repository) -> int:
    """Dismiss many Impacts at once — the burst gesture (e.g. after a backfill
    approval floods the inbox). Returns how many were dismissed (issue #18).
    """
    dismissed = repo.bulk_set_impact_state(impact_ids, "dismissed")
    repo.commit()
    logger.info("bulk-dismissed %d impact(s)", dismissed)
    return dismissed


# -- helpers ----------------------------------------------------------------


def _detect_forward(
    source_type: str,
    source_id: int,
    judge: StanceJudge,
    repo: Repository,
    candidate_limit: int,
) -> list[int]:
    """Weigh one new Claim/Protocol against every anchor it overlaps by Concept."""
    knowledge = repo.load_impact_knowledge(source_type, source_id)
    if knowledge is None:
        return []
    raised: list[int] = []
    for anchor in repo.impact_anchor_candidates(
        source_type, source_id, limit=candidate_limit
    ):
        stance = _stance(judge, knowledge, anchor)
        if stance is None:
            continue
        impact_id = repo.add_impact(
            source_type, source_id, anchor.type, anchor.id, stance
        )
        if impact_id is not None:
            raised.append(impact_id)
    return raised


def _stance(judge: StanceJudge, knowledge, anchor) -> str | None:
    """Judge one pair, returning a persistable Stance or ``None`` to discard it.

    `unrelated` — and any out-of-vocabulary return — discards the pair, so a sloppy
    judgement can never mint an Impact the table's CHECK would reject anyway.
    """
    stance = judge.judge(knowledge, anchor)
    if stance not in STANCES:
        return None
    return stance


def _transition(impact_id: int, state: str, repo: Repository) -> bool:
    if repo.set_impact_state(impact_id, state):
        repo.commit()
        logger.info("impact %s -> %s", impact_id, state)
        return True
    repo.rollback()
    return False
